#! /bin/sh

# mount /proc and /sys from fstab
/bin/mount -a

# mount /dev and /boot
echo /sbin/mdev >/proc/sys/kernel/hotplug
/sbin/mdev -s

/sbin/syslogd -C # circular buffer - use logread to read
/sbin/klogd      # log kernel messages - also available in dmesg

# create vchiq device
[ -x /etc/init.d/vchiq ] && /etc/init.d/vchiq start
echo
echo Greetings from standalone Raspberry Pi
echo

sh /etc/rc.local 

# use an artificial SysRq-g to interrupt
# echo Attempting to enter the debugger! ....
# echo g > /proc/sysrq-trigger
